// Code generated by MockGen. DO NOT EDIT.
// Source: call_external_api.go

// Package main is a generated GoMock package.
package main

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockExtApiCall is a mock of ExtApiCall interface.
type MockExtApiCall struct {
	ctrl     *gomock.Controller
	recorder *MockExtApiCallMockRecorder
}

// MockExtApiCallMockRecorder is the mock recorder for MockExtApiCall.
type MockExtApiCallMockRecorder struct {
	mock *MockExtApiCall
}

// NewMockExtApiCall creates a new mock instance.
func NewMockExtApiCall(ctrl *gomock.Controller) *MockExtApiCall {
	mock := &MockExtApiCall{ctrl: ctrl}
	mock.recorder = &MockExtApiCallMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExtApiCall) EXPECT() *MockExtApiCallMockRecorder {
	return m.recorder
}

// CallApi mocks base method.
func (m *MockExtApiCall) CallApi(request *ExtRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CallApi", request)
	ret0, _ := ret[0].(error)
	return ret0
}

// CallApi indicates an expected call of CallApi.
func (mr *MockExtApiCallMockRecorder) CallApi(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CallApi", reflect.TypeOf((*MockExtApiCall)(nil).CallApi), request)
}
